// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBxCq7D9KEZ_PqDWtsLfoX6yDESHtSrEqo',
    appId: '1:451392714870:web:fddf2d882889a874a44757',
    messagingSenderId: '451392714870',
    projectId: 'mytiktokclone-f9789',
    authDomain: 'mytiktokclone-f9789.firebaseapp.com',
    databaseURL: 'https://mytiktokclone-f9789-default-rtdb.firebaseio.com',
    storageBucket: 'mytiktokclone-f9789.firebasestorage.app',
    measurementId: 'G-RJEWD61T4V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAtFUnFsWWReLKSF701shXNZN7I_dckqcY',
    appId: '1:451392714870:android:7487299ed8c09eada44757',
    messagingSenderId: '451392714870',
    projectId: 'mytiktokclone-f9789',
    databaseURL: 'https://mytiktokclone-f9789-default-rtdb.firebaseio.com',
    storageBucket: 'mytiktokclone-f9789.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD-UpLUgZUtp78Lb4cspNSg24VlEt86FXE',
    appId: '1:451392714870:ios:fae12ce43e20c8e7a44757',
    messagingSenderId: '451392714870',
    projectId: 'mytiktokclone-f9789',
    databaseURL: 'https://mytiktokclone-f9789-default-rtdb.firebaseio.com',
    storageBucket: 'mytiktokclone-f9789.firebasestorage.app',
    androidClientId: '451392714870-7hce1ith76jlj2p12ial1po87pvms846.apps.googleusercontent.com',
    iosClientId: '451392714870-ou81enrikugt84aejoejfd24n866b6mp.apps.googleusercontent.com',
    iosBundleId: 'com.example.toptopFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD-UpLUgZUtp78Lb4cspNSg24VlEt86FXE',
    appId: '1:451392714870:ios:fae12ce43e20c8e7a44757',
    messagingSenderId: '451392714870',
    projectId: 'mytiktokclone-f9789',
    databaseURL: 'https://mytiktokclone-f9789-default-rtdb.firebaseio.com',
    storageBucket: 'mytiktokclone-f9789.firebasestorage.app',
    androidClientId: '451392714870-7hce1ith76jlj2p12ial1po87pvms846.apps.googleusercontent.com',
    iosClientId: '451392714870-ou81enrikugt84aejoejfd24n866b6mp.apps.googleusercontent.com',
    iosBundleId: 'com.example.toptopFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBxCq7D9KEZ_PqDWtsLfoX6yDESHtSrEqo',
    appId: '1:451392714870:web:41e1d2052dcd5d69a44757',
    messagingSenderId: '451392714870',
    projectId: 'mytiktokclone-f9789',
    authDomain: 'mytiktokclone-f9789.firebaseapp.com',
    databaseURL: 'https://mytiktokclone-f9789-default-rtdb.firebaseio.com',
    storageBucket: 'mytiktokclone-f9789.firebasestorage.app',
    measurementId: 'G-WPW8XL1Z7N',
  );
}
